### ISSUE TITLE
Organiser's checklist (logistics)

### ISSUE THREAD

**Issue by npscience** [open-data-day-cambridge-2018/open-data-day-cambridge-2018.github.io#9]
From ODD guide:

- [x] A lot of spaces to plug in electronic devices or the ability to place more power strips out --> we have power strips
- [x] A projector and screen
- [ ] Dongles or adapters, because different devices need different plugs --> or just share from Naomi's macbook
- [ ] Name badges or identifiers for people to know their abilities --> sticky labels? We have coloured sharpies
- [ ] Snacks, water, etc --> see Catering #5 
- [ ] USB Drives --> bring a couple?
- [x] Directional signage. Bathrooms, workshop rooms, etc --> not needed, small venue
- [ ] Wi-Fi and the password for everyone --> details to be shared during intro
- [x] Registration for your event --> share Eventbrite when ready
- [x] Open Data Day logo

For venue:

- [ ] print sign-up list and check in/out
- [x] ensure all know where fire exits are and what to do in the event of a fire --> in intro talk
- [x] make sure they know where the toilets are --> intro talk
- [ ] No smoking allowed on site --> add to intro talk
- [ ] request additional cleaning

**Comment by npscience** [comment]
I’ll revisit this tomorrow with venue specific things - revisited

**Comment by yochannah** [comment]
Event is over! :)
